const D=window.ISLAMIC_DATA;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const surahNames=["الفاتحة","البقرة","آل عمران","النساء","المائدة","الأنعام","الأعراف","الأنفال","التوبة","يونس","هود","يوسف","الرعد","إبراهيم","الحجر","النحل","الإسراء","الكهف","مريم","طه","الأنبياء","الحج","المؤمنون","النور","الفرقان","الشعراء","النمل","القصص","العنكبوت","الروم","لقمان","السجدة","الأحزاب","سبأ","فاطر","يس","الصافات","ص","الزمر","غافر","فصلت","الشورى","الزخرف","الدخان","الجاثية","الأحقاف","محمد","الفتح","الحجرات","ق","الذاريات","الطور","النجم","القمر","الرحمن","الواقعة","الحديد","المجادلة","الحشر","الممتحنة","الصف","الجمعة","المنافقون","التغابن","الطلاق","التحريم","الملك","القلم","الحاقة","المعارج","نوح","الجن","المزمل","المدثر","القيامة","الإنسان","المرسلات","النبأ","النازعات","عبس","التكوير","الانفطار","المطففين","الانشقاق","البروج","الطارق","الأعلى","الغاشية","الفجر","البلد","الشمس","الليل","الضحى","الشرح","التين","العلق","القدر","البينة","الزلزلة","العاديات","القارعة","التكاثر","العصر","الهمزة","الفيل","قريش","الماعون","الكوثر","الكافرون","النصر","المسد","الإخلاص","الفلق","الناس"];
let currentAdhkarCat='الصباح',currentDuaCat='قرآنية';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function esc(s){return String(s).replaceAll('\\','\\\\').replaceAll('"','&quot;').replaceAll("'","&#39;").replace(/\n/g,' ')}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show');window.scrollTo({top:0,behavior:'smooth'});if(id==='favorites')renderFavorites();if(id==='khatma')renderKhatma();if(id==='quran'&&!qState.ayahs.length)loadQuranPage(qState.page)}
$$('#nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.section));$$('[data-open]').forEach(b=>b.onclick=()=>showPage(b.dataset.open));
$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#overlay').classList.toggle('show')};$('#overlay').onclick=()=>{$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');$('[data-go="daily"]').onclick=()=>$('#daily').scrollIntoView({behavior:'smooth'});

function daily(){const k=Math.floor(Date.now()/86400000),a=D.dailyAyahs[k%D.dailyAyahs.length],h=D.hadiths[k%D.hadiths.length],cats=Object.keys(D.adhkar),dcat=Object.keys(D.duas);$('#dailyAyah').textContent=a.t;$('#dailyAyahRef').textContent=a.r;$('#dailyDhikr').textContent=D.adhkar[cats[k%cats.length]][0][0];$('#dailyHadith').textContent=h[1];$('#dailyHadithRef').textContent=h[2];$('#dailyDua').textContent=D.duas[dcat[k%dcat.length]][0][0];$('#homeAdhkarCount').textContent=Object.values(D.adhkar).reduce((n,x)=>n+x.length,0);$('#homeHadithCount').textContent=D.hadiths.length}daily();

// -------------------- المصحف: صفحات + سور كاملة + أجزاء --------------------
$('#surahSelect').innerHTML=surahNames.map((n,i)=>`<option value="${i+1}">${i+1}. سورة ${n}</option>`).join('');
$('#juzSelect').innerHTML=Array.from({length:30},(_,i)=>`<option value="${i+1}">الجزء ${i+1}</option>`).join('');
const reciterBitrate={"ar.alafasy":128,"ar.husary":128,"ar.minshawi":128,"ar.hudhaify":128,"ar.sudais":192,"ar.abdulbasit":192,"ar.shuraim":128,"legacy.mustafa":128,"legacy.refat":128};
const legacySurahReciters={"legacy.mustafa":"https://server8.mp3quran.net/mustafa/","legacy.refat":"https://server14.mp3quran.net/refat/"};
const everyAyahReciters={"ar.sudais":"Abdurrahmaan_As-Sudais_192kbps","ar.abdulbasit":"Abdul_Basit_Murattal_192kbps","ar.shuraim":"Saood_ash-Shuraym_128kbps"};
function pad3(n){return String(Number(n)||0).padStart(3,'0')}
function ayahAudioSources(ayah,rec){const bit=reciterBitrate[rec]||128,sources=[];if(everyAyahReciters[rec]&&ayah?.surah?.number&&ayah?.numberInSurah)sources.push(`https://everyayah.com/data/${everyAyahReciters[rec]}/${pad3(ayah.surah.number)}${pad3(ayah.numberInSurah)}.mp3`);sources.push(`https://cdn.islamic.network/quran/audio/${bit}/${rec}/${ayah.number}.mp3`,`https://cdn.alislam.ru/quran/audio/${bit}/${rec}/${ayah.number}.mp3`);return sources}
const qState={mode:'page',page:Number(localStorage.lastQuranPage||1),juz:1,ayahs:[],surahs:[],audioCtx:null,audioSources:[],audioTimer:null,audioStarted:0,audioTotal:0,audioRanges:[],fallbackPlayer:null,currentSurah:1};
async function fetchJSON(url){const r=await fetch(url);if(!r.ok)throw Error('network');const j=await r.json();if(j.code&&j.code!==200)throw Error('api');return j}
function pageCacheKey(p){return `quranPage:v61:${p}`}
let fullQuranPromise=null;
async function getFullQuranAyahs(){
  if(fullQuranPromise)return fullQuranPromise;
  fullQuranPromise=(async()=>{
    const cached=sessionStorage.getItem('quranFull:v61');
    if(cached){try{return JSON.parse(cached)}catch{}}
    const j=await fetchJSON('https://api.alquran.cloud/v1/quran/quran-uthmani');
    const ayahs=[];
    (j.data?.surahs||[]).forEach(s=>{
      (s.ayahs||[]).forEach(a=>ayahs.push({...a,surah:{number:s.number,name:s.name,englishName:s.englishName,englishNameTranslation:s.englishNameTranslation,revelationType:s.revelationType}}));
    });
    try{sessionStorage.setItem('quranFull:v61',JSON.stringify(ayahs))}catch{}
    return ayahs;
  })();
  try{return await fullQuranPromise}catch(e){fullQuranPromise=null;throw e}
}
async function getPageData(p){
  const key=pageCacheKey(p),cached=sessionStorage.getItem(key);
  if(cached){try{return JSON.parse(cached)}catch{}}
  try{
    const j=await fetchJSON(`https://api.alquran.cloud/v1/page/${p}/quran-uthmani`);
    if(j?.data?.ayahs?.length){sessionStorage.setItem(key,JSON.stringify(j.data));return j.data}
  }catch{}
  const all=await getFullQuranAyahs(),ayahs=all.filter(a=>Number(a.page)===Number(p));
  if(!ayahs.length)throw new Error('page-empty');
  const data={number:Number(p),ayahs};
  try{sessionStorage.setItem(key,JSON.stringify(data))}catch{}
  return data;
}
async function getSurahAyahs(n){
  try{const j=await fetchJSON(`https://api.alquran.cloud/v1/surah/${n}/quran-uthmani`);if(j?.data?.ayahs?.length)return j.data.ayahs.map(a=>({...a,surah:{number:j.data.number,name:j.data.name,englishName:j.data.englishName,englishNameTranslation:j.data.englishNameTranslation,revelationType:j.data.revelationType}}))}catch{}
  const all=await getFullQuranAyahs();return all.filter(a=>a.surah.number===Number(n));
}
async function getJuzAyahs(n){
  try{const j=await fetchJSON(`https://api.alquran.cloud/v1/juz/${n}/quran-uthmani`);if(j?.data?.ayahs?.length)return j.data.ayahs}catch{}
  const all=await getFullQuranAyahs();return all.filter(a=>Number(a.juz)===Number(n));
}
function stopSurahPlayer(){const p=$('#surahPlayer');if(!p)return;p.pause();p.removeAttribute('src');p.load()}
function setQuranMode(mode){qState.mode=mode;$$('.quran-mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const cfg={page:['وضع الصفحات','التنقل الآن صفحة بصفحة'],surah:['وضع السورة الكاملة','السورة المختارة تظهر كاملة دون تقسيمها إلى صفحات'],juz:['وضع الجزء الكامل','الجزء المختار يظهر كاملًا ويمكن الانتقال بين الأجزاء']}[mode];$('#readingModeBadge').textContent=cfg[0];$('#readingModeHelp').textContent=cfg[1];$('#autoNextWrap').classList.toggle('hidden',mode!=='page');$('#mushafPage').classList.toggle('long-reading',mode!=='page');$('#mushafPage').classList.toggle('surah-reading',mode==='surah');$('#mushafPage').classList.toggle('juz-reading',mode==='juz');localStorage.quranBrowseMode=mode}
function renderMushafPage(ayahs){let html='',lastSurah=null;ayahs.forEach(a=>{if(a.surah.number!==lastSurah){lastSurah=a.surah.number;html+=`<div class="surah-banner">سُورَةُ ${surahNames[lastSurah-1]}</div>`;if(a.numberInSurah===1&&lastSurah!==1&&lastSurah!==9)html+='<div class="basmala">بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</div>'}let text=a.text;if(a.numberInSurah===1&&lastSurah!==1&&lastSurah!==9)text=text.replace(/^بِسْمِ[^]+?الرَّحِيمِ\s*/,'');html+=`<span class="mushaf-ayah" data-global="${a.number}" data-page="${a.page||''}">${text} <span class="mushaf-ayah-mark">${a.numberInSurah}</span> </span>`});$('#mushafPage').innerHTML=`<p class="mushaf-text">${html}</p>`}
function setNavDisabled(prevDisabled,nextDisabled){$('#prevPage').disabled=$('#prevPageBottom').disabled=prevDisabled;$('#nextPage').disabled=$('#nextPageBottom').disabled=nextDisabled}
async function loadQuranPage(page){page=Math.max(1,Math.min(604,Number(page)||1));stopPageAudio();stopSurahPlayer();setQuranMode('page');qState.page=page;localStorage.lastQuranPage=page;$('#pageJump').value=page;$('#mushafPageTitle').textContent=`الصفحة ${page}`;$('#pageNumberBottom').textContent=`صفحة ${page}`;$('#mushafMeta').textContent='جارٍ تحميل الصفحة...';$('#mushafPage').innerHTML='<div class="notice">جارٍ تحميل نص الصفحة...</div>';setNavDisabled(page===1,page===604);try{const data=await getPageData(page),ayahs=data.ayahs||[];qState.ayahs=ayahs;qState.surahs=[...new Set(ayahs.map(a=>a.surah.number))];qState.currentSurah=qState.surahs[0]||1;qState.juz=ayahs[0]?.juz||1;$('#surahSelect').value=qState.currentSurah;$('#juzSelect').value=qState.juz;const metaSurahs=qState.surahs.map(n=>`سورة ${surahNames[n-1]}`).join(' • ');$('#mushafMeta').textContent=`${metaSurahs} — الجزء ${qState.juz}`;renderMushafPage(ayahs);updateLastReadUI()}catch(e){$('#mushafPage').innerHTML='<div class="notice">تعذر تحميل صفحة المصحف الآن. تأكد من الإنترنت ثم أعد المحاولة.</div>';$('#mushafMeta').textContent='تعذر التحميل'}}
async function loadQuranSurah(n){n=Math.max(1,Math.min(114,Number(n)||1));stopPageAudio();stopSurahPlayer();setQuranMode('surah');qState.currentSurah=n;localStorage.lastQuranSurah=n;$('#surahSelect').value=n;$('#mushafPageTitle').textContent=`سورة ${surahNames[n-1]} كاملة`;$('#pageNumberBottom').textContent=`${n} / 114`;$('#mushafMeta').textContent='جارٍ تحميل السورة كاملة...';$('#mushafPage').innerHTML='<div class="notice">جارٍ تحميل السورة كاملة...</div>';setNavDisabled(n===1,n===114);try{const ayahs=await getSurahAyahs(n);qState.ayahs=ayahs;qState.surahs=[n];qState.page=ayahs[0]?.page||qState.page;qState.juz=ayahs[0]?.juz||1;$('#pageJump').value=qState.page;$('#juzSelect').value=qState.juz;$('#mushafMeta').textContent=`${ayahs.length} آية — تبدأ من صفحة ${ayahs[0]?.page||'—'} — الجزء ${qState.juz}`;renderMushafPage(ayahs)}catch(e){$('#mushafPage').innerHTML='<div class="notice">تعذر تحميل السورة كاملة الآن.</div>';$('#mushafMeta').textContent='تعذر التحميل'}}
async function loadQuranJuz(n){n=Math.max(1,Math.min(30,Number(n)||1));stopPageAudio();stopSurahPlayer();setQuranMode('juz');qState.juz=n;localStorage.lastQuranJuz=n;$('#juzSelect').value=n;$('#mushafPageTitle').textContent=`الجزء ${n} كاملًا`;$('#pageNumberBottom').textContent=`جزء ${n} / 30`;$('#mushafMeta').textContent='جارٍ تحميل الجزء كاملًا...';$('#mushafPage').innerHTML='<div class="notice">جارٍ تحميل الجزء كاملًا...</div>';setNavDisabled(n===1,n===30);try{const ayahs=await getJuzAyahs(n);qState.ayahs=ayahs;qState.surahs=[...new Set(ayahs.map(a=>a.surah.number))];qState.currentSurah=qState.surahs[0]||1;qState.page=ayahs[0]?.page||qState.page;$('#pageJump').value=qState.page;$('#surahSelect').value=qState.currentSurah;$('#mushafMeta').textContent=`${ayahs.length} آية — ${qState.surahs.map(x=>surahNames[x-1]).join(' • ')}`;renderMushafPage(ayahs)}catch(e){$('#mushafPage').innerHTML='<div class="notice">تعذر تحميل الجزء كاملًا الآن.</div>';$('#mushafMeta').textContent='تعذر التحميل'}}
function gotoQuran(delta){if(qState.mode==='surah')return loadQuranSurah(qState.currentSurah+delta);if(qState.mode==='juz')return loadQuranJuz(qState.juz+delta);return loadQuranPage(qState.page+delta)}
$('#prevPage').onclick=$('#prevPageBottom').onclick=()=>gotoQuran(-1);$('#nextPage').onclick=$('#nextPageBottom').onclick=()=>gotoQuran(1);
$('#goPage').onclick=()=>loadQuranPage($('#pageJump').value);$('#pageJump').onkeydown=e=>{if(e.key==='Enter')loadQuranPage(e.target.value)};
$('#surahSelect').onchange=e=>loadQuranSurah(e.target.value);$('#juzSelect').onchange=e=>loadQuranJuz(e.target.value);
$('#modePage').onclick=()=>loadQuranPage(qState.page);$('#modeSurah').onclick=()=>loadQuranSurah(qState.currentSurah);$('#modeJuz').onclick=()=>loadQuranJuz(qState.juz);
$('#savePage').onclick=()=>{const p=qState.ayahs[0]?.page||qState.page;localStorage.savedQuranPage=p;localStorage.lastQuranPage=p;renderKhatma();toast(`تم حفظ موضع القراءة عند الصفحة ${p}`)};
function playSurahContinuous(n=qState.currentSurah){
  stopPageAudio();
  const rec=$('#reciter').value,bit=reciterBitrate[rec]||128,player=$('#surahPlayer');
  const sources=legacySurahReciters[rec]
    ? [`${legacySurahReciters[rec]}${pad3(n)}.mp3`]
    : [
      `https://cdn.islamic.network/quran/audio-surah/${bit}/${rec}/${n}.mp3`,
      `https://cdn.alislam.ru/quran/audio-surah/${bit}/${rec}/${n}.mp3`
    ];
  let sourceIndex=0,finished=false;
  const cleanup=()=>{player.onerror=null;player.oncanplay=null;player.onplaying=null};
  const fallback=()=>{
    cleanup();
    if(finished)return;
    finished=true;
    $('#pageAudioStatus').textContent='تعذر ملف السورة المتصل؛ سيتم تشغيل الآيات بالتتابع.';
    toast('تم التحويل تلقائيًا إلى تشغيل الآيات');
    playAyahSequence();
  };
  const trySource=()=>{
    if(sourceIndex>=sources.length)return fallback();
    player.pause();
    player.src=sources[sourceIndex++];
    player.load();
    $('#pageAudioStatus').textContent=`جارٍ تجهيز سورة ${surahNames[n-1]} بصوت متصل...`;
    player.onerror=()=>setTimeout(trySource,120);
    player.oncanplay=()=>{
      if(finished)return;
      $('#pageAudioStatus').textContent=`تشغيل سورة ${surahNames[n-1]} كاملة بصوت متصل`;
      player.play().catch(()=>{if(sourceIndex<sources.length)trySource();else fallback()});
    };
    player.onplaying=()=>{finished=true;cleanup()};
  };
  trySource();
}
$('#playCurrentSurah').onclick=()=>playSurahContinuous(qState.currentSurah);
$('#reciter').onchange=()=>{stopPageAudio();stopSurahPlayer()};
function trimAudioBuffer(ctx,buffer){const sr=buffer.sampleRate,ch0=buffer.getChannelData(0),threshold=.0035;let start=0,end=ch0.length-1;while(start<end&&Math.abs(ch0[start])<threshold)start++;while(end>start&&Math.abs(ch0[end])<threshold)end--;const pad=Math.floor(sr*.025);start=Math.max(0,start-pad);end=Math.min(ch0.length-1,end+pad);const len=Math.max(1,end-start+1),out=ctx.createBuffer(buffer.numberOfChannels,len,sr);for(let c=0;c<buffer.numberOfChannels;c++)out.copyToChannel(buffer.getChannelData(c).slice(start,end+1),c);return out}
async function loadAyahBuffer(ctx,ayah,rec){let lastErr;for(const url of ayahAudioSources(ayah,rec)){try{const r=await fetch(url);if(!r.ok)throw Error('audio');const arr=await r.arrayBuffer();const decoded=await ctx.decodeAudioData(arr);return trimAudioBuffer(ctx,decoded)}catch(e){lastErr=e}}throw lastErr||Error('audio')}
function highlightAudioAyah(i){$$('.mushaf-ayah').forEach(x=>x.classList.remove('current-audio-ayah'));const el=$$('.mushaf-ayah')[i];if(el){el.classList.add('current-audio-ayah');if(qState.mode!=='page'&&i%5===0)el.scrollIntoView({behavior:'smooth',block:'center'})}}
async function playPageSeamless(){stopPageAudio();if(!qState.ayahs.length)return;const btn=$('#playPage');btn.disabled=true;$('#pageAudioStatus').textContent='جارٍ تجهيز تلاوة الصفحة لتعمل متصلة...';try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)throw Error('noctx');const ctx=new AudioCtx();qState.audioCtx=ctx;if(ctx.state==='suspended')await ctx.resume();const rec=$('#reciter').value,buffers=[];for(let i=0;i<qState.ayahs.length;i++){$('#pageAudioStatus').textContent=`تجهيز تلاوة الصفحة... ${i+1} من ${qState.ayahs.length}`;buffers.push(await loadAyahBuffer(ctx,qState.ayahs[i],rec))}let t=ctx.currentTime+.12,total=0;qState.audioSources=[];qState.audioRanges=[];buffers.forEach((buf,i)=>{const src=ctx.createBufferSource();src.buffer=buf;src.connect(ctx.destination);src.start(t+total);qState.audioSources.push(src);qState.audioRanges.push([total,total+buf.duration,i]);total+=buf.duration});qState.audioStarted=ctx.currentTime+.12;qState.audioTotal=total;$('#pageAudioStatus').textContent=`تشغيل الصفحة ${qState.page} — تلاوة متصلة`;qState.audioTimer=setInterval(()=>{if(!qState.audioCtx)return;const elapsed=Math.max(0,qState.audioCtx.currentTime-qState.audioStarted),pct=Math.min(100,(elapsed/qState.audioTotal)*100);$('#pageAudioProgress').style.width=pct+'%';const range=qState.audioRanges.find(r=>elapsed>=r[0]&&elapsed<r[1]);if(range)highlightAudioAyah(range[2]);if(elapsed>=qState.audioTotal){stopPageAudio(false);$('#pageAudioStatus').textContent=`انتهت الصفحة ${qState.page}`;if($('#autoNextPage').checked&&qState.page<604){loadQuranPage(qState.page+1).then(()=>setTimeout(playPageSeamless,450))}}},180)}catch(e){$('#pageAudioStatus').textContent='تعذر تشغيل وضع الصفحة المتصل على هذا المتصفح. سيتم استخدام التشغيل المتتابع.';playAyahSequence()}finally{btn.disabled=false}}
function playAyahSequence(){stopPageAudio();const rec=$('#reciter').value;let i=0,sourceIndex=0,sources=[];const a=new Audio();qState.fallbackPlayer=a;const finish=()=>{qState.fallbackPlayer=null;$('#pageAudioStatus').textContent='انتهت التلاوة';if(qState.mode==='page'&&$('#autoNextPage').checked&&qState.page<604)loadQuranPage(qState.page+1)};const trySource=()=>{if(!sources.length||sourceIndex>=sources.length){i++;return next()}a.src=sources[sourceIndex++];a.load();a.play().catch(()=>{if(qState.fallbackPlayer===a)setTimeout(trySource,80)})};const next=()=>{if(i>=qState.ayahs.length)return finish();const ayah=qState.ayahs[i];highlightAudioAyah(i);$('#pageAudioStatus').textContent=qState.mode==='juz'?`تشغيل الجزء ${qState.juz} — الآية ${i+1} من ${qState.ayahs.length}`:`تشغيل الآية ${i+1} من ${qState.ayahs.length}`;sources=ayahAudioSources(ayah,rec);sourceIndex=0;trySource()};a.onended=()=>{i++;next()};a.onerror=()=>{if(qState.fallbackPlayer===a)setTimeout(trySource,80)};next()}
function stopPageAudio(reset=true){if(qState.audioTimer){clearInterval(qState.audioTimer);qState.audioTimer=null}qState.audioSources.forEach(s=>{try{s.stop()}catch{}});qState.audioSources=[];if(qState.audioCtx){try{qState.audioCtx.close()}catch{}qState.audioCtx=null}if(qState.fallbackPlayer){qState.fallbackPlayer.pause();qState.fallbackPlayer=null}$$('.mushaf-ayah').forEach(x=>x.classList.remove('current-audio-ayah'));if(reset){$('#pageAudioProgress').style.width='0%';$('#pageAudioStatus').textContent='تم إيقاف التلاوة.'}}
$('#playPage').onclick=()=>{if(qState.mode==='surah')return playSurahContinuous(qState.currentSurah);if(qState.mode==='juz')return playAyahSequence();playPageSeamless()};$('#stopPage').onclick=()=>{stopPageAudio();stopSurahPlayer()};
$('#quranSearchBtn').onclick=searchQuran;$('#quranSearch').onkeydown=e=>{if(e.key==='Enter')searchQuran()};async function searchQuran(){const q=$('#quranSearch').value.trim(),box=$('#quranSearchResults');if(q.length<2)return toast('اكتب كلمتين على الأقل للبحث');box.classList.remove('hidden');box.innerHTML='<div class="notice">جارٍ البحث في القرآن...</div>';try{const j=await fetchJSON(`https://api.alquran.cloud/v1/search/${encodeURIComponent(q)}/all/ar`),m=(j.data.matches||[]).slice(0,25);box.innerHTML=m.length?m.map(x=>`<button class="search-result" data-g="${x.number||x.ayah?.number||''}"><b>${surahNames[(x.surah?.number||1)-1]}: ${x.numberInSurah||x.ayah?.numberInSurah||''}</b><span>${x.text}</span><small>اضغط لفتح موضع الآية في المصحف</small></button>`).join(''):'<div class="notice">لا توجد نتائج.</div>';box.querySelectorAll('[data-g]').forEach(b=>b.onclick=async()=>{try{const aj=await fetchJSON(`https://api.alquran.cloud/v1/ayah/${b.dataset.g}/quran-uthmani`);loadQuranPage(aj.data.page)}catch{toast('تعذر فتح موضع الآية')}})}catch{box.innerHTML='<div class="notice">تعذر البحث الآن.</div>'}}
function updateLastReadUI(){
  const p=Math.max(1,Math.min(604,Number(localStorage.lastQuranPage||1)));
  const label=$('#lastReadLabel');
  if(label)label.textContent=`آخر قراءة: الصفحة ${p}`;
  const b=$('#continueReading');
  if(b)b.textContent=`متابعة الصفحة ${p}`;
  renderHomeKhatma();
}
function renderKhatma(){const p=Math.max(0,Math.min(604,Number(localStorage.savedQuranPage||localStorage.lastQuranPage||0))),pct=p?Math.round((p/604)*100):0,daily=Math.max(1,Number(localStorage.dailyPages||10));$('#khatmaCurrentPage').value=p||'';$('#dailyPages').value=daily;$('#khatmaPercent').textContent=pct+'%';$('#khatmaPages').textContent=`${p} من 604 صفحة`;$('#khatmaBar').style.width=pct+'%';const remaining=Math.max(0,604-p),days=Math.ceil(remaining/daily);$('#khatmaEstimate').textContent=remaining?`بمعدل ${daily} صفحات يوميًا، يتبقى تقريبًا ${days} يومًا لإتمام الختمة بإذن الله.`:'أتممت تسجيل صفحات الختمة. تقبل الله.';const start=p+1,end=Math.min(604,p+daily);$('#todayTarget').textContent=p<604?`${start} — ${end}`:'تمت الختمة';updateLastReadUI()}
function renderHomeKhatma(){const p=Math.max(0,Math.min(604,Number(localStorage.savedQuranPage||0))),pct=p?Math.round((p/604)*100):0;$('#homeKhatmaTitle').textContent=p?`وصلت إلى الصفحة ${p}`:'ابدأ ختمتك';$('#homeKhatmaText').textContent=p?`أنجزت ${pct}% من صفحات المصحف.`:'يمكنك حفظ آخر صفحة ومتابعة وردك يوميًا.';$('#homeKhatmaBar').style.width=pct+'%'}
$('#saveKhatma').onclick=()=>{const p=Math.max(1,Math.min(604,Number($('#khatmaCurrentPage').value)||1));localStorage.savedQuranPage=p;localStorage.lastQuranPage=p;renderKhatma();toast('تم حفظ تقدم الختمة')};$('#saveDailyPages').onclick=()=>{localStorage.dailyPages=Math.max(1,Math.min(100,Number($('#dailyPages').value)||10));renderKhatma();toast('تم حفظ الورد اليومي')};$('#openKhatmaPage').onclick=()=>{showPage('quran');loadQuranPage(Number(localStorage.savedQuranPage||localStorage.lastQuranPage||1))};$('#resumeLastRead').onclick=$('#continueReading').onclick=()=>{showPage('quran');loadQuranPage(Number(localStorage.lastQuranPage||1))};renderKhatma();

// -------------------- الأذكار والأدعية والأحاديث --------------------
function buildTabs(container,obj,cb){const keys=Object.keys(obj);container.innerHTML=keys.map((k,i)=>`<button class="${i?'':'active'}" data-k="${k}">${k}</button>`).join('');container.querySelectorAll('button').forEach(b=>b.onclick=()=>{container.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');cb(b.dataset.k)});return keys[0]}
function renderAdhkar(cat){currentAdhkarCat=cat;const q=$('#adhkarSearch').value.trim(),list=$('#adhkarList');list.innerHTML='';D.adhkar[cat].forEach((z,i)=>{if(q&&!`${z[0]} ${z[2]}`.includes(q))return;let key=`dhikr:${cat}:${i}`,count=Number(localStorage[key]||0),art=document.createElement('article');art.innerHTML=`<div class="item-head"><span class="tag">${cat}</span><div class="item-actions"><button class="fav">☆</button><button class="shr">↗</button></div></div><p>${z[0]}</p><small class="source">${z[2]}</small><div class="counter-row"><small>التكرار: ${z[1]}</small><button class="counter-btn">${count>=z[1]?'✓ تم':count+' / '+z[1]}</button></div>`;const btn=art.querySelector('.counter-btn');btn.onclick=()=>{count=Math.min(z[1],count+1);localStorage[key]=count;btn.textContent=count>=z[1]?'✓ تم':`${count} / ${z[1]}`};art.querySelector('.fav').onclick=()=>favItem('ذكر',z[0],z[2]);art.querySelector('.shr').onclick=()=>shareText(`${z[0]}\n${z[2]}`);list.appendChild(art)});if(!list.children.length)list.innerHTML='<div class="notice">لا توجد نتائج في هذا القسم.</div>'}
let firstA=buildTabs($('#adhkarTabs'),D.adhkar,renderAdhkar);renderAdhkar(firstA);$('#adhkarSearch').oninput=()=>renderAdhkar(currentAdhkarCat);$('#resetAdhkarToday').onclick=()=>{D.adhkar[currentAdhkarCat].forEach((_,i)=>localStorage.removeItem(`dhikr:${currentAdhkarCat}:${i}`));renderAdhkar(currentAdhkarCat);toast('تم تصفير عدادات القسم')};
function renderDuas(cat){currentDuaCat=cat;const q=$('#duaSearch').value.trim(),list=$('#duaList');list.innerHTML='';D.duas[cat].forEach(d=>{if(q&&!`${d[0]} ${d[1]}`.includes(q))return;const a=document.createElement('article');a.innerHTML=`<div class="item-head"><span class="tag">${cat}</span><div class="item-actions"><button class="fav">☆</button><button class="shr">↗</button></div></div><p class="quran-text">${d[0]}</p><small class="source">${d[1]}</small>`;a.querySelector('.fav').onclick=()=>favItem('دعاء',d[0],d[1]);a.querySelector('.shr').onclick=()=>shareText(`${d[0]}\n${d[1]}`);list.appendChild(a)});if(!list.children.length)list.innerHTML='<div class="notice">لا توجد نتائج في هذا القسم.</div>'}
let firstD=buildTabs($('#duaTabs'),D.duas,renderDuas);renderDuas(firstD);$('#duaSearch').oninput=()=>renderDuas(currentDuaCat);
const hadithCats=[...new Set(D.hadiths.map(h=>h[0]))].sort();$('#hadithCategory').innerHTML='<option value="all">كل الموضوعات</option>'+hadithCats.map(c=>`<option>${c}</option>`).join('');function renderHadith(){let q=$('#hadithSearch').value.trim(),c=$('#hadithCategory').value,list=$('#hadithList');list.innerHTML='';D.hadiths.filter(h=>(c==='all'||h[0]===c)&&(!q||h.join(' ').includes(q))).forEach(h=>{const a=document.createElement('article');a.innerHTML=`<div class="item-head"><span class="tag">${h[0]}</span><div class="item-actions"><button class="fav">☆</button><button class="shr">↗</button></div></div><p>${h[1]}</p><small class="source">${h[2]}</small>`;a.querySelector('.fav').onclick=()=>favItem('حديث',h[1],h[2]);a.querySelector('.shr').onclick=()=>shareText(`${h[1]}\n${h[2]}`);list.appendChild(a)});if(!list.children.length)list.innerHTML='<div class="notice">لا توجد نتائج مطابقة.</div>'}renderHadith();$('#hadithSearch').oninput=renderHadith;$('#hadithCategory').onchange=renderHadith;

const ruqyah=[
['الفاتحة','بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ','سورة الفاتحة — ثبتت الرقية بها في الصحيح'],
['آية الكرسي',D.adhkar['الصباح'][0][0].replace('آية الكرسي: ',''),'البقرة: 255'],
['الإخلاص',D.adhkar['الصباح'][1][0],'سورة الإخلاص'],['الفلق',D.adhkar['الصباح'][2][0],'سورة الفلق'],['الناس',D.adhkar['الصباح'][3][0],'سورة الناس'],
['دعاء الشفاء','أَذْهِبِ البَأْسَ رَبَّ النَّاسِ، اشْفِ أَنْتَ الشَّافِي، لا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لا يُغَادِرُ سَقَمًا.','صحيح البخاري وصحيح مسلم'],
['الرقية النبوية','بِسْمِ اللهِ أَرْقِيكَ، مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ، مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ، اللهُ يَشْفِيكَ، بِسْمِ اللهِ أَرْقِيكَ.','صحيح مسلم']
];$('#ruqyahList').innerHTML=ruqyah.map(x=>`<article><span class="tag">${x[0]}</span><p class="quran-text">${x[1]}</p><small class="source">${x[2]}</small></article>`).join('');

// -------------------- المفضلة والمشاركة والسبحة --------------------
function getFavs(){try{return JSON.parse(localStorage.favorites||'[]')}catch{return[]}}window.favItem=(type,text,ref)=>{let a=getFavs();if(!a.some(x=>x.text===text)){a.unshift({type,text,ref});localStorage.favorites=JSON.stringify(a);toast('تمت الإضافة للمفضلة')}else toast('موجود بالفعل في المفضلة')};function renderFavorites(){const a=getFavs(),l=$('#favoriteList');if(!a.length){l.innerHTML='<div class="notice">لم تحفظ أي محتوى بعد. اضغط ☆ بجوار أي ذكر أو دعاء أو حديث.</div>';return}l.innerHTML='';a.forEach((x,i)=>{const e=document.createElement('article');e.innerHTML=`<div class="item-head"><span class="tag">${x.type}</span><button class="remove">حذف</button></div><p>${x.text}</p><small class="source">${x.ref||''}</small>`;e.querySelector('.remove').onclick=()=>{a.splice(i,1);localStorage.favorites=JSON.stringify(a);renderFavorites()};l.appendChild(e)})}
window.shareText=async text=>{try{if(navigator.share)await navigator.share({title:'صدقة جارية على روح الحاج فتحي العيسوي',text,url:location.href});else{await navigator.clipboard.writeText(text+'\n'+location.href);toast('تم نسخ النص والرابط')}}catch{}};$('#shareSite').onclick=$('#shareMemorial').onclick=()=>shareText('صدقة جارية على روح الحاج فتحي العيسوي — قرآن بالصفحات وأذكار وأدعية وأحاديث ومواقيت الصلاة.');
let tas=Number(localStorage.tasbeeh||0);function paintTas(){$('#tasbeehCount').textContent=tas;localStorage.tasbeeh=tas}paintTas();$('#tasbeehTap').onclick=()=>{tas++;paintTas()};$('#minusTasbeeh').onclick=()=>{tas=Math.max(0,tas-1);paintTas()};$('#resetTasbeeh').onclick=()=>{tas=0;paintTas()};$('#tasbeehPhrase').onchange=()=>{tas=0;paintTas()};

// -------------------- الصلاة والقبلة --------------------
const pNames={Fajr:'الفجر',Sunrise:'الشروق',Dhuhr:'الظهر',Asr:'العصر',Maghrib:'المغرب',Isha:'العشاء'};let prayerCountdownTimer=null;
const egyptCities={
Cairo:[30.0444,31.2357],Giza:[30.0131,31.2089],Alexandria:[31.2001,29.9187],"Port Said":[31.2653,32.3019],Suez:[29.9668,32.5498],Ismailia:[30.5965,32.2715],Mansoura:[31.0409,31.3785],Tanta:[30.7865,31.0004],Zagazig:[30.5877,31.5020],Damanhur:[31.0341,30.4682],Damietta:[31.4165,31.8133],Fayoum:[29.3084,30.8428],"Beni Suef":[29.0661,31.0994],Minya:[28.0871,30.7618],Asyut:[27.1809,31.1837],Sohag:[26.5591,31.6957],Qena:[26.1551,32.7160],Luxor:[25.6872,32.6396],Aswan:[24.0889,32.8998],Hurghada:[27.2579,33.8116],"Sharm El Sheikh":[27.9158,34.3300],Arish:[31.1321,33.8033]
};
function parseTime(t){return String(t).split(' ')[0]}
function egyptClockDate(){const now=new Date(),p=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(now),g=k=>Number(p.find(x=>x.type===k)?.value||0);return new Date(g('year'),g('month')-1,g('day'),g('hour'),g('minute'),g('second'))}
function updateNextPrayer(timings){if(prayerCountdownTimer)clearInterval(prayerCountdownTimer);const order=['Fajr','Dhuhr','Asr','Maghrib','Isha'];const tick=()=>{const now=egyptClockDate();let next=null,nextDate=null;for(const k of order){const [h,m]=parseTime(timings[k]).split(':').map(Number),d=new Date(now);d.setHours(h,m,0,0);if(d>now){next=k;nextDate=d;break}}if(!next){next='Fajr';const [h,m]=parseTime(timings.Fajr).split(':').map(Number);nextDate=new Date(now);nextDate.setDate(nextDate.getDate()+1);nextDate.setHours(h,m,0,0)}const ms=nextDate-now,hh=Math.floor(ms/3600000),mm=Math.floor((ms%3600000)/60000),ss=Math.floor((ms%60000)/1000);$('#nextPrayerName').textContent=pNames[next];$('#nextPrayerCountdown').textContent=`متبقي ${hh}س ${mm}د ${ss}ث بتوقيت مصر`;$('#homePrayerTitle').textContent=`الصلاة القادمة في مصر: ${pNames[next]}`;$('#homePrayerText').textContent=`متبقي ${hh} ساعة و${mm} دقيقة`};tick();prayerCountdownTimer=setInterval(tick,1000)}
function rad(x){return x*Math.PI/180}function deg(x){return x*180/Math.PI}function fixAngle(a){return ((a%360)+360)%360}function fixHour(a){return ((a%24)+24)%24}
function cairoOffset(date=new Date()){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date),g=k=>Number(p.find(x=>x.type===k)?.value||0),asUTC=Date.UTC(g('year'),g('month')-1,g('day'),g('hour'),g('minute'),g('second'));return (asUTC-date.getTime())/3600000}
function julianDate(y,m,d){if(m<=2){y-=1;m+=12}const A=Math.floor(y/100),B=2-A+Math.floor(A/4);return Math.floor(365.25*(y+4716))+Math.floor(30.6001*(m+1))+d+B-1524.5}
function sunPosition(jd){const D=jd-2451545.0,g=fixAngle(357.529+0.98560028*D),q=fixAngle(280.459+0.98564736*D),L=fixAngle(q+1.915*Math.sin(rad(g))+0.020*Math.sin(rad(2*g))),e=23.439-0.00000036*D,RA=fixHour(deg(Math.atan2(Math.cos(rad(e))*Math.sin(rad(L)),Math.cos(rad(L))))/15),eqt=q/15-RA,decl=deg(Math.asin(Math.sin(rad(e))*Math.sin(rad(L))));return{decl,eqt}}
function hourAngle(lat,decl,alt){const c=(Math.sin(rad(alt))-Math.sin(rad(lat))*Math.sin(rad(decl)))/(Math.cos(rad(lat))*Math.cos(rad(decl)));return deg(Math.acos(Math.max(-1,Math.min(1,c))))/15}
function fmtHour(h){h=fixHour(h);let hh=Math.floor(h),mm=Math.round((h-hh)*60);if(mm===60){hh=(hh+1)%24;mm=0}return `${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`}
function localEgyptPrayerTimes(lat,lon,date=new Date()){
 const ep=egyptClockDate(),y=ep.getFullYear(),m=ep.getMonth()+1,d=ep.getDate(),jd=julianDate(y,m,d)-lon/(15*24),s=sunPosition(jd),tz=cairoOffset(date),noon=12-s.eqt+(tz-lon/15),fajr=noon-hourAngle(lat,s.decl,-19.5),sunrise=noon-hourAngle(lat,s.decl,-0.833),maghrib=noon+hourAngle(lat,s.decl,-0.833),isha=noon+hourAngle(lat,s.decl,-17.5),asrAlt=-deg(Math.atan(1/(1+Math.tan(rad(Math.abs(lat-s.decl)))))),asr=noon+hourAngle(lat,s.decl,asrAlt);
 return{Fajr:fmtHour(fajr),Sunrise:fmtHour(sunrise),Dhuhr:fmtHour(noon),Asr:fmtHour(asr),Maghrib:fmtHour(maghrib),Isha:fmtHour(isha)}
}
function localHijri(){try{return new Intl.DateTimeFormat('ar-EG-u-ca-islamic-umalqura',{timeZone:'Africa/Cairo',day:'numeric',month:'long',year:'numeric'}).format(new Date()).replace('هـ','').trim()+' هـ'}catch{return '—'}}
function qiblaBearing(lat,lon){const kaLat=rad(21.422487),kaLon=rad(39.826206),pLat=rad(lat),dLon=kaLon-rad(lon);return fixAngle(deg(Math.atan2(Math.sin(dLon),Math.cos(pLat)*Math.tan(kaLat)-Math.sin(pLat)*Math.cos(dLon))))}
function paintPrayer(t,label,lat,lon,hijri,source){$('#hijriDate').textContent=hijri||localHijri();$('#prayerStatus').textContent=`${label} — بتوقيت مصر — طريقة الهيئة المصرية العامة للمساحة${source==='local'?' (حساب احتياطي داخل الموقع)':''}`;$('#prayerGrid').innerHTML=Object.keys(pNames).map(k=>`<div class="prayer"><b>${pNames[k]}</b><span>${parseTime(t[k])}</span></div>`).join('');updateNextPrayer(t);const bearing=qiblaBearing(lat,lon);$('#qiblaBox').classList.remove('hidden');$('#qiblaDeg').textContent=`${bearing.toFixed(1)}° من الشمال`;$('#qiblaArrow').style.transform=`rotate(${bearing}deg)`}
async function renderPrayer(city,label,coords){const [lat,lon]=coords;$('#prayerStatus').textContent='جارٍ تحميل مواقيت '+label+' بتوقيت مصر...';try{const url=`https://api.aladhan.com/v1/timings/${Math.floor(Date.now()/1000)}?latitude=${lat}&longitude=${lon}&method=5&school=0`,j=await fetchJSON(url),t=j.data.timings,h=`${j.data.date.hijri.day} ${j.data.date.hijri.month.ar} ${j.data.date.hijri.year} هـ`;paintPrayer(t,label,lat,lon,h,'api')}catch{const t=localEgyptPrayerTimes(lat,lon);paintPrayer(t,label,lat,lon,localHijri(),'local')}}
$('#cityPrayerBtn').onclick=()=>{const c=$('#egyptCity'),city=c.value,label=c.options[c.selectedIndex].text,coords=egyptCities[city]||egyptCities.Cairo;localStorage.egyptCity=city;renderPrayer(city,label,coords)};
$('#locateBtn').onclick=()=>{if(!navigator.geolocation)return $('#prayerStatus').textContent='المتصفح لا يدعم تحديد الموقع.';$('#prayerStatus').textContent='جارٍ تحديد موقعك داخل مصر...';navigator.geolocation.getCurrentPosition(pos=>{const{latitude,longitude}=pos.coords;if(latitude<21.5||latitude>32.2||longitude<24||longitude>37.2){$('#prayerStatus').textContent='موقعك الحالي خارج مصر. اختر مدينة مصرية من القائمة لعرض مواقيت مصر.';return}renderPrayer('location','موقعك داخل مصر',[latitude,longitude])},()=>$('#prayerStatus').textContent='تعذر الحصول على الموقع. اختر مدينة مصرية من القائمة.',{enableHighAccuracy:true,timeout:12000})};if(localStorage.egyptCity&&egyptCities[localStorage.egyptCity])$('#egyptCity').value=localStorage.egyptCity;setTimeout(()=>$('#cityPrayerBtn').click(),400);

// -------------------- فوائد / بحث / الصدقة --------------------
$('#benefitList').innerHTML=D.benefits.map((b,i)=>`<article><span class="tag">فائدة ${i+1}</span><p>${b}</p></article>`).join('');$('#duaForFather').onclick=()=>{localStorage.fatherDuas=Number(localStorage.fatherDuas||0)+1;$('#duaThanks').textContent='تقبّل الله دعاءك وجزاك خيرًا.'};
function allSearchItems(){let a=[];Object.entries(D.adhkar).forEach(([c,v])=>v.forEach(x=>a.push(['ذكر — '+c,x[0],x[2]])));Object.entries(D.duas).forEach(([c,v])=>v.forEach(x=>a.push(['دعاء — '+c,x[0],x[1]])));D.hadiths.forEach(h=>a.push(['حديث — '+h[0],h[1],h[2]]));ruqyah.forEach(x=>a.push(['رقية — '+x[0],x[1],x[2]]));return a}const searchItems=allSearchItems();$('#globalSearchBtn').onclick=()=>{$('#searchModal').classList.remove('hidden');setTimeout(()=>$('#globalSearch').focus(),50)};$('#closeSearch').onclick=()=>$('#searchModal').classList.add('hidden');$('#searchModal').onclick=e=>{if(e.target.id==='searchModal')$('#searchModal').classList.add('hidden')};$('#globalSearch').oninput=e=>{let q=e.target.value.trim();$('#searchResults').innerHTML=q?searchItems.filter(x=>x.join(' ').includes(q)).slice(0,35).map(x=>`<article><span class="tag">${x[0]}</span><p>${x[1]}</p><small class="source">${x[2]}</small></article>`).join(''):'<div class="notice">اكتب كلمة للبحث في الأذكار والأدعية والأحاديث والرقية.</div>'};

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
updateLastReadUI();renderHomeKhatma();const savedMode=localStorage.quranBrowseMode||'page';if(savedMode==='surah')loadQuranSurah(Number(localStorage.lastQuranSurah||1));else if(savedMode==='juz')loadQuranJuz(Number(localStorage.lastQuranJuz||1));else loadQuranPage(qState.page);

// -------------------- V5: عرض المصحف / أسماء الله / أعمال اليوم --------------------
(function initMushafView(){
  const page=$('#mushafPage'), classic=$('#mushafClassic'), comfort=$('#mushafComfort');
  if(!page||!classic||!comfort)return;
  let mode=localStorage.mushafView||'classic', size=Number(localStorage.mushafFont||36);
  const apply=()=>{page.classList.toggle('comfort',mode==='comfort');classic.classList.toggle('active',mode==='classic');comfort.classList.toggle('active',mode==='comfort');page.style.setProperty('--mushaf-font',`${size}px`)};
  classic.onclick=()=>{mode='classic';localStorage.mushafView=mode;apply()};comfort.onclick=()=>{mode='comfort';localStorage.mushafView=mode;apply()};
  $('#fontUp').onclick=()=>{size=Math.min(42,size+2);localStorage.mushafFont=size;apply()};$('#fontDown').onclick=()=>{size=Math.max(22,size-2);localStorage.mushafFont=size;apply()};apply();
})();

const ASMA_FALLBACK=['الله','الرحمن','الرحيم','الملك','القدوس','السلام','المؤمن','المهيمن','العزيز','الجبار','المتكبر','الخالق','البارئ','المصور','الغفار','القهار','الوهاب','الرزاق','الفتاح','العليم','القابض','الباسط','الخافض','الرافع','المعز','المذل','السميع','البصير','الحكم','العدل','اللطيف','الخبير','الحليم','العظيم','الغفور','الشكور','العلي','الكبير','الحفيظ','المقيت','الحسيب','الجليل','الكريم','الرقيب','المجيب','الواسع','الحكيم','الودود','المجيد','الباعث','الشهيد','الحق','الوكيل','القوي','المتين','الولي','الحميد','المحصي','المبدئ','المعيد','المحيي','المميت','الحي','القيوم','الواجد','الماجد','الواحد','الأحد','الصمد','القادر','المقتدر','المقدم','المؤخر','الأول','الآخر','الظاهر','الباطن','الوالي','المتعالي','البر','التواب','المنتقم','العفو','الرؤوف','مالك الملك','ذو الجلال والإكرام','المقسط','الجامع','الغني','المغني','المانع','الضار','النافع','النور','الهادي','البديع','الباقي','الوارث','الرشيد','الصبور'];
let asmaItems=ASMA_FALLBACK.map((name,i)=>({name,number:i+1}));
function renderAsma(filter=''){const grid=$('#asmaGrid');if(!grid)return;const q=filter.trim();grid.innerHTML=asmaItems.filter(x=>!q||x.name.includes(q)||String(x.number)===q).map(x=>`<article class="asma-card"><small>${x.number}</small><b>${x.name}</b></article>`).join('')||'<div class="notice">لا توجد نتيجة مطابقة.</div>'}
renderAsma();if($('#asmaSearch'))$('#asmaSearch').oninput=e=>renderAsma(e.target.value);if($('#randomAsma'))$('#randomAsma').onclick=()=>{const x=asmaItems[Math.floor(Math.random()*asmaItems.length)],box=$('#asmaFeatured');box.classList.remove('hidden');box.innerHTML=`<small>اسم للتدبر اليوم</small><b>${x.name}</b><p>تأمل هذا الاسم، وادعُ الله به بما يناسب حاجتك مع تعظيمه وحسن الظن به.</p>`;box.scrollIntoView({behavior:'smooth',block:'center'})};

function dailyWorksState(){const today=new Date().toISOString().slice(0,10);let s={date:today,done:[]};try{s=JSON.parse(localStorage.dailyWorks||'{}')}catch{}if(s.date!==today)s={date:today,done:[]};return s}
function renderDailyWorks(){const list=$('#dailyWorksList');if(!list||!D.dailyWorks)return;const s=dailyWorksState();list.innerHTML='';D.dailyWorks.forEach((w,i)=>{const done=s.done.includes(i),el=document.createElement('label');el.className='daily-work'+(done?' done':'');el.innerHTML=`<input type="checkbox" ${done?'checked':''}><div><span>${w[0]}</span><small>${w[1]}</small></div>`;el.querySelector('input').onchange=e=>{const st=dailyWorksState();if(e.target.checked&&!st.done.includes(i))st.done.push(i);if(!e.target.checked)st.done=st.done.filter(n=>n!==i);localStorage.dailyWorks=JSON.stringify(st);renderDailyWorks()};list.appendChild(el)});const n=s.done.length,total=D.dailyWorks.length,pct=Math.round(n/total*100);$('#dailyWorksPercent').textContent=pct+'%';$('#dailyWorksDone').textContent=`${n} / ${total}`;$('#dailyWorksBar').style.width=pct+'%'}
renderDailyWorks();if($('#resetDailyWorks'))$('#resetDailyWorks').onclick=()=>{localStorage.removeItem('dailyWorks');renderDailyWorks();toast('تم بدء قائمة يوم جديد')};
